#!/usr/bin/env python3
from __future__ import annotations

import argparse
import asyncio
import json
from pathlib import Path

import numpy as np
from isaacsim.simulation_app import SimulationApp


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Capture fixed comparison screenshots for the forest digital twin demo.")
    parser.add_argument(
        "--manifest",
        type=Path,
        default=Path(
            "/home/prefor/IsaacForestSim/data/forest_twin/forest_demo_manifest.json"),
        help="Manifest generated by forest_env_demo.py.",
    )
    parser.add_argument("--twin-usd", type=Path, default=None,
                        help="Override the generated digital twin USD path.")
    parser.add_argument("--pointcloud-usd", type=Path, default=None,
                        help="Override the point cloud preview USD path.")
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("/home/prefor/IsaacForestSim/data/forest_twin/captures"),
        help="Directory that will receive the PNG captures.",
    )
    parser.add_argument("--width", type=int, default=1600)
    parser.add_argument("--height", type=int, default=900)
    return parser.parse_args()


async def _wait_updates(count: int) -> None:
    import omni.kit.app

    app = omni.kit.app.get_app()
    for _ in range(max(1, int(count))):
        await app.next_update_async()


async def capture_stage(stage_path: Path, output_dir: Path, prefix: str, presets: list[dict[str, object]]) -> None:
    import omni.usd
    from isaacsim.core.utils.viewports import set_camera_view
    from omni.kit.viewport.utility import get_active_viewport
    import omni.kit.viewport_legacy
    import omni.renderer_capture
    from pxr import Sdf, UsdGeom

    context = omni.usd.get_context()
    print(f"Opening stage: {stage_path}")
    if not context.open_stage(str(stage_path)):
        raise RuntimeError(f"failed to open stage: {stage_path}")
    await _wait_updates(20)
    print(f"Stage opened: {stage_path}")

    stage = context.get_stage()
    camera_path = "/World/CaptureCamera"
    camera = UsdGeom.Camera.Define(stage, Sdf.Path(camera_path))
    camera.CreateClippingRangeAttr((0.01, 10000.0))
    camera.CreateFocalLengthAttr(28.0)

    viewport = get_active_viewport()
    if viewport is None:
        raise RuntimeError("no active viewport available for capture")
    if hasattr(viewport, "camera_path"):
        viewport.camera_path = camera_path
    if hasattr(viewport, "updates_enabled"):
        viewport.updates_enabled = True

    viewport_interface = omni.kit.viewport_legacy.acquire_viewport_interface()
    renderer_capture = omni.renderer_capture.acquire_renderer_capture_interface()

    async def capture_png(file_path: Path) -> None:
        resource = None
        attempts = 0
        while resource is None:
            window = viewport_interface.get_viewport_window(None)
            resource = None if window is None else window.get_drawable_ldr_resource()
            if resource is None:
                attempts += 1
                if attempts > 120:
                    raise TimeoutError(
                        f"viewport render resource was not ready for {file_path}")
                await _wait_updates(2)
        print(f"Capturing: {file_path}")
        renderer_capture.capture_next_frame_rp_resource(
            str(file_path), resource)
        await _wait_updates(2)
        renderer_capture.wait_async_capture()
        await _wait_updates(2)
        print(f"Captured: {file_path}")

    for preset in presets:
        name = str(preset["name"])
        eye = np.asarray(preset["eye"], dtype=np.float64)
        target = np.asarray(preset["target"], dtype=np.float64)
        set_camera_view(eye=eye, target=target,
                        camera_prim_path=camera_path, viewport_api=viewport)
        if hasattr(viewport, "camera_path"):
            viewport.camera_path = camera_path
        await _wait_updates(8)
        file_path = output_dir / f"{prefix}_{name}.png"
        print(f"View: {prefix}/{name}")
        await capture_png(file_path)


def load_manifest(manifest_path: Path) -> dict:
    if not manifest_path.exists():
        raise FileNotFoundError(f"missing manifest: {manifest_path}")
    return json.loads(manifest_path.read_text(encoding="utf-8"))


def main() -> int:
    args = parse_args()
    manifest = load_manifest(args.manifest.resolve())
    twin_usd = (args.twin_usd.resolve() if args.twin_usd is not None else Path(
        manifest["output_usd"]).resolve())
    pointcloud_usd = (
        args.pointcloud_usd.resolve()
        if args.pointcloud_usd is not None
        else Path(manifest["options"]["pointcloud_preview_usd"]).resolve()
    )
    presets = list(manifest.get("camera_presets") or manifest.get(
        "options", {}).get("preview_camera_presets") or [])
    if not presets:
        raise RuntimeError("manifest does not contain camera presets")

    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    simulation_app = SimulationApp(
        {
            "headless": False,
            "width": int(args.width),
            "height": int(args.height),
            "renderer": "RayTracedLighting",
        }
    )
    try:
        asyncio.get_event_loop().run_until_complete(capture_stage(
            pointcloud_usd, output_dir, "pointcloud", presets))
        asyncio.get_event_loop().run_until_complete(
            capture_stage(twin_usd, output_dir, "twin", presets))
        print(f"Wrote captures to: {output_dir}")
        return 0
    finally:
        simulation_app.close()


if __name__ == "__main__":
    raise SystemExit(main())
